# Generated by Django 2.1.2 on 2019-05-20 11:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('name_of_taxpayer', models.CharField(default='', max_length=80)),
                ('upload_document', models.FileField(upload_to='documents/')),
                ('time_collected', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('recieving_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='letter_officer_recieving_files', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Letter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
