# Generated by Django 2.1.2 on 2019-05-20 10:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('', ''), ('LTD', 'Limited'), ('ENT', 'Enterprise')], default='', max_length=3)),
                ('created_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('name_of_taxpayer', models.CharField(default='', max_length=80)),
                ('tin', models.CharField(max_length=15)),
                ('year', models.PositiveIntegerField(blank=True, default='2019', null=True)),
                ('location_of_business', models.CharField(max_length=52)),
                ('contact_number', models.CharField(max_length=16, null=True)),
                ('upload_document', models.FileField(upload_to='documents/')),
                ('time_collected', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('recieving_officer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_officer_recieving_files', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Entry', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'managed': True,
            },
        ),
    ]
