# Generated by Django 2.1.2 on 2019-06-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tcc',
            name='name_of_company',
            field=models.CharField(default='', max_length=80, null=True),
        ),
    ]
